export const Types = {
	LOGIN: 'LOGIN',
	SIGNUP: 'SIGNUP',
	DELETEUSER: 'DELETEUSER',
	LISTUSER: 'LISTUSER',
	MAKEADMIN: 'MAKEADMIN',
	REMOVEADMIN: 'REMOVEADMIN',
	LOGOUT: 'LOGOUT',
	ADDTASK: 'ADDTASK',
	LISTASK: 'LISTASK',
	DELETETASK: 'DELETETASK',
	UPDATETASK: 'UPDATETASK'

}
